micronaut:
  application:
    name: tccmicronaut
netty:
  default:
    allocator:
      max-order: 3

datasources:
    default:
        url: jdbc:postgresql://localhost:5432/tccspringboot
        username: postgres
        password: admin
        driverClassName: org.postgresl.Driver
        dialect: POSTGRES

jpa:
  default:
    entity-scan:
      packages: 'com.tccmicronaut'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
  
          
  
       