micronaut:
  application:
    name: tccmicronaut
netty:
  default:
    allocator:
      max-order: 3

datasources:
    default:
        url: jdbc:postgresql://localhost:5432/tccspringboot
        username: postgres
        password: 'admin'
        driverClassName: org.postgresql.Driver
        dialect: postgres
        schema-generate: CREATE_DROP

jpa:
  default:
    entity-scan:
        packages: 'com.tccmicronaut.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
  
       